import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Github, Twitter, Globe, Mail, Shield, Clock, AlertTriangle } from "lucide-react"

export function Footer() {
  const currentYear = new Date().getFullYear()

  const footerLinks = {
    Product: [
      { name: "Features", href: "#activity" },
      { name: "Risk Detection", href: "#risk" },
      { name: "Watchlist", href: "#watchlist" },
      { name: "Search", href: "#search" },
    ],
    Resources: [
      { name: "Documentation", href: "#" },
      { name: "API Reference", href: "#" },
      { name: "Tutorials", href: "#" },
      { name: "Blog", href: "#" },
    ],
    Company: [
      { name: "About", href: "#" },
      { name: "Careers", href: "#" },
      { name: "Contact", href: "#" },
      { name: "Support", href: "#" },
    ],
    Legal: [
      { name: "Privacy Policy", href: "#" },
      { name: "Terms of Service", href: "#" },
      { name: "Cookie Policy", href: "#" },
      { name: "Disclaimer", href: "#" },
    ],
  }

  const socialLinks = [
    { name: "GitHub", icon: Github, href: "#" },
    { name: "Twitter", icon: Twitter, href: "#" },
    { name: "Website", icon: Globe, href: "#" },
    { name: "Email", icon: Mail, href: "#" },
  ]

  return (
    <footer className="bg-background/95 backdrop-blur-sm border-t border-border/50 mt-20">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Main Footer Content */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8 mb-12">
          {/* Brand Section */}
          <div className="lg:col-span-1">
            <div className="flex items-center space-x-2 mb-4">
              <div className="text-2xl font-bold font-serif text-primary neon-text">🔗 ChainSage</div>
            </div>
            <p className="text-sm text-muted-foreground mb-6 leading-relaxed">
              Real-time on-chain intelligence platform for blockchain monitoring, risk detection, and security analysis.
            </p>
            <div className="flex space-x-3">
              {socialLinks.map((social) => {
                const Icon = social.icon
                return (
                  <a
                    key={social.name}
                    href={social.href}
                    className="p-2 rounded-lg bg-card/50 border border-border/50 hover:bg-primary/10 hover:border-primary/50 transition-all duration-200 group"
                    aria-label={social.name}
                  >
                    <Icon className="h-4 w-4 text-muted-foreground group-hover:text-primary" />
                  </a>
                )
              })}
            </div>
          </div>

          {/* Footer Links */}
          {Object.entries(footerLinks).map(([category, links]) => (
            <div key={category}>
              <h3 className="font-semibold text-foreground mb-4">{category}</h3>
              <ul className="space-y-3">
                {links.map((link) => (
                  <li key={link.name}>
                    <a
                      href={link.href}
                      className="text-sm text-muted-foreground hover:text-primary transition-colors duration-200"
                    >
                      {link.name}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Disclaimer Section */}
        <Card className="bg-card/30 border-border/50 mb-8">
          <div className="p-6">
            <div className="flex items-start space-x-3">
              <AlertTriangle className="h-5 w-5 text-orange-400 flex-shrink-0 mt-0.5" />
              <div>
                <h4 className="font-semibold text-foreground mb-2">Important Disclaimer</h4>
                <div className="text-sm text-muted-foreground space-y-2 leading-relaxed">
                  <p>
                    ChainSage provides blockchain data analysis for informational purposes only. All data is sourced
                    from third-party APIs and may experience delays or inaccuracies.
                  </p>
                  <p>
                    Risk scores and alerts are generated by automated algorithms and should not be considered as
                    financial advice. Always conduct your own research before making any investment decisions.
                  </p>
                  <p>
                    Data latency may vary between 30 seconds to 5 minutes depending on the data source and network
                    conditions. Critical alerts are prioritized for faster delivery.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Card>

        {/* Status Indicators */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
          <div className="flex items-center space-x-6">
            <div className="flex items-center space-x-2">
              <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
              <span className="text-sm text-muted-foreground">API Status: Operational</span>
            </div>
            <div className="flex items-center space-x-2">
              <Clock className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">Last Update: 30s ago</span>
            </div>
            <div className="flex items-center space-x-2">
              <Shield className="h-4 w-4 text-primary" />
              <span className="text-sm text-muted-foreground">Security: Active</span>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <Badge variant="outline" className="text-xs bg-background/50">
              v1.0.0
            </Badge>
            <Badge variant="outline" className="text-xs bg-background/50">
              Beta
            </Badge>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t border-border/50">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="text-sm text-muted-foreground">
              © {currentYear} ChainSage. All rights reserved. Built with v0 by Vercel.
            </div>
            <div className="flex items-center space-x-6 text-sm text-muted-foreground">
              <span>Powered by Ethereum, Polygon, BSC, Arbitrum</span>
              <div className="flex items-center space-x-2">
                <div className="w-1.5 h-1.5 bg-primary rounded-full"></div>
                <span>Multi-chain Support</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
